#!/bin/bash

function manage_app () {
    python manage.py makemigrations
    python manage.py migrate
    python manage.py collectstatic  \
      --no-input --verbosity 2 \
      --traceback \
      -i django_extensions \
      -i '*.coffee' \
      -i '*.rb' \
      -i '*.scss' \
      -i '*.less' \
      -i '*.sass'
}

function start_production() {
    # use gunicorn for production server here
    manage_app
    gunicorn config.wsgi -w 4 -b 0.0.0.0:8000 --chdir=/app --log-file -
}

start_production

