name: Django CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.7-slim-buster
      volumes:
      - /cache/pip:/github/home/.cache/pip
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgis/postgis:11-3.0
        env:
          POSTGRES_HOST: 'postgres'
          POSTGRES_DB: 'postgres'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /github/home/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/common.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install System Depedencies
      run: |
        apt-get update && apt-get install -y build-essential libpq-dev binutils libproj-dev gdal-bin
    - name: Install Project Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/common.txt
        pip install -r requirements/testing.txt
    - name: Run Tests
      run: |
        pytest
      env:
        DJANGO_ENV: 'testing'
        DJANGO_HOSTNAME: 'http://test.server'
        POSTGRES_HOST: 'postgres'
        POSTGRES_DB: 'postgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_PORT: 5432
